spring.application.name=viora-platform
documentation.application.description=Plataforma Viora - Gestion Agricola de Olivos
documentation.application.version=1.0.0
documentation.application.title=Viora API