spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USER}
spring.datasource.password=${DATABASE_PASSWORD}

spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

springdoc.api-docs.enabled=${OPENAPI_ENABLED:false}
springdoc.swagger-ui.enabled=${OPENAPI_ENABLED:false}

server.port=${PORT:8080}