spring.datasource.url=jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:viora}
spring.datasource.username=${DATABASE_USER:viora_app}
spring.datasource.password=${DATABASE_PASSWORD:Viora_Local_2026}

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

server.port=${PORT:8080}